baseURL = "https://cyberblog-kalaimaran.netlify.app/"
languageCode = "en-us"
title = "Cybersecurity Blog"
theme = "tailbliss"

[params]
  description = "My cybersecurity walkthroughs and learning logs"
  author = "Kalaimaran"
  favicon = "favicon.ico"

[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1

  [[menu.main]]
    name   = "Posts"
    url    = "/posts/"
    weight = 2

  [[menu.main]]
    name   = "About"
    url    = "/about/"
    weight = 3


ignoreLogs = ["warning-goldmark-raw-html"]

